### ISSUE TITLE
You took my project!

### ISSUE THREAD

**Issue by Catfan67** [mcedit/mcedit2#122]
I used MCEdit to move a Rainbow Road track I built a short distance, but when I opened the world, the track and almost everything else in my world that I built were GONE! Now I'm really mad! >:(

**Comment by Catfan67** [comment]
By the way, I misplaced what was left, so I just deleted the world. I just figured I'd tell you that MCEdit's move feature may be somewhat buggy.

**Comment by codewarrior0** [comment]
Version number?

**Comment by Catfan67** [comment]
Windows x64 v 2.0.0 alpha-467 (I think)

**Comment by codewarrior0** [comment]
All right. I don't know how to reproduce this, and it sounds like you don't have the original save file any more.

I'm guessing that when you say the stuff you built is "GONE!", you mean those parts of the world were replaced with natural terrain. I know that Minecraft will reset the chunks to natural terrain if it finds unexpected data in them, and I think this happens if you open a world from Minecraft 1.8 in an earlier Minecraft version. 

I recently did some work on converting 1.8 items to 1.7 to make it possible to move things between versions. Maybe that's where something is going wrong.

If you can reliably reproduce the issue and possibly narrow it down to certain things being moved and not others, any info about that would be helpful, as would a copy of the save file where it occurs.

**Comment by Catfan67** [comment]
Well, I see that there is a folder in my "saves" folder called ##Ryan's
World.UNDO##, so that could be something useful. Do you know anything about
it?

On Thu, Jun 18, 2015 at 6:14 PM, David Vierra <notifications@github.com>
wrote:

> All right. I don't know how to reproduce this, and it sounds like you
> don't have the original save file any more.
>
> I'm guessing that when you say the stuff you built is "GONE!", you mean
> those parts of the world were replaced with natural terrain. I know that
> Minecraft will reset the chunks to natural terrain if it finds unexpected
> data in them, and I think this happens if you open a world from Minecraft
> 1.8 in an earlier Minecraft version.
>
> I recently did some work on converting 1.8 items to 1.7 to make it
> possible to move things between versions. Maybe that's where something is
> going wrong.
>
> If you can reliably reproduce the issue and possibly narrow it down to
> certain things being moved and not others, any info about that would be
> helpful, as would a copy of the save file where it occurs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcedit/mcedit2/issues/122#issuecomment-113315130>.
>



-- 
Ryan Strobach
YouTube/Google+: +Catfan67 Plays / Ryan Strobach
Email: IAmRyanStrobach@gmail.com
Minecraft: Catfan67
Roblox: itsamemario12345
