### ISSUE TITLE
AttributeError: 'PySide.QtOpenGL.QGLContext' object has no attribute 'setData'

### ISSUE THREAD

**Issue by iLeevi** [mcedit/mcedit2#126]
When mcedit is loading world mcedit will crash!
Log (mcedit.txt file): http://pastebin.com/kbZRaQGP
Mcedit version: 2.0.0alpha-472

**Comment by codewarrior0** [comment]
Does this happen every time you open MCEdit?

**Comment by tibo204** [comment]
me too ! 
i try opening all mc version , but it not working.
Mcedit version: 2.0.0alpha-472

**Comment by codewarrior0** [comment]
Again, does it happen every time you open MCEdit?

I've seen this bug in maybe one out of twenty times I launch MCEdit, so I'm having trouble finding out the cause.

**Comment by tibo204** [comment]
ok!. i reinstall and i work :)

**Comment by codewarrior0** [comment]
As far as I can figure, this is a bug in PySide.

When QGLWidget.context() is called, it creates a PyObject wrapper for the C++ QGLContext. This wrapper is registered with the BindingManager so that if any virtual methods are overridden on the Python side, they will be called from the C++ side. With the caveat that they will only be called from the C++ side if the object that has the virtual methods was also created on the Python side via a Python constructor.

So because the C++ QGLContext was created by QGLWidget and not on the Python side, this wrapper registration is a wasted effort. 

When the QGLContext's PyObject wrapper is freed, its entry is not unregistered from the BindingManager for unknown reasons.

Later, a QStandardItem's PyObject wrapper is created at the same address. Because it is created on the Python side, it actually wraps a C++ subclass of QStandardItem that is able to dispatch its virtual methods through the PyObject wrapper. But the dispatch fails because BindingManager still references the QGLContext wrapper at the previous address. The error occurs when it tries to dispatch 'getData' through this zombie wrapper.

**Comment by codewarrior0** [comment]
I determined that the QGLContext's PyObject wrapper is not being freed. The QGLWidget's wrapper keeps a reference to it.

This means when the QStandardItem is created on the Python side, its wrapper is being created at the same address as the QGLContext's wrapper? This is getting confusing.

**Comment by codewarrior0** [comment]
Can you test the latest `master` and see if this still happens? You may want to close and relaunch MCEdit a few times, since it doesn't happen every time.

**Comment by codewarrior0** [comment]
[I hope this fixes it.](https://github.com/PySide/Shiboken/issues/74)

**Comment by codewarrior0** [comment]
Definitely fixed. 

Well, only for Windows. Linux guys will have to recompile PySide with the fix...
