### ISSUE TITLE
Suggestion: Moving to a new Schematic format for Minecraft 1.8+ support

### ISSUE THREAD

**Issue by gabizou** [mcedit/mcedit2#239]
As some people may be aware, Minecraft's internals moved from using a pair of int ids, representing a `block id` and `metadata`, to `BlockState`s, a table based system of `block id` and property/value pairs. In storage, to avoid an entire world format change, they are still serialized back to their original int id pairs, but, schematics can greatly benefit by moving away from such systems.

SpongePowered has developed a [work-in-progress API](https://github.com/SpongePowered/SpongeAPI/compare/bleeding...feature/schematics) and [implementation](https://github.com/SpongePowered/SpongeCommon/compare/bleeding...feature/schematics) in support of a new [Schematic format](https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-1.md) that aims to take advantage of a Palette system to reduce schematic sizes. Likewise, this format takes advantage of not requiring modded block id's to be re-assigned or "fixed' when importing between servers/installations/versions since the state id's already provide all the information required.

The major advantage of this new format is that adding various metadata, such as versions will help introduce a more stable and future compatible system for various implementations using said format to reduce user maintenance of older schematics.

There was some [discussion about the palette system used](https://github.com/PaperMC/Paper/issues/330), and the [results are quite illuminating](https://gist.github.com/Deamon5550/4303bb3e462f7a35991a1081d00368db).

The largest benefit of all of this new schematic format is improved versioning support when importing schematics into worlds with various implementations (such as Sponge or Paper or WorldEdit).

**Comment by codewarrior0** [comment]
I have already implemented BlockState mapping into the schematic format used by MCEdit 2. It is backwards-compatible with old MCEdit 1 and WorldEdit schematics, given that you are importing back into the same world from which you exported. The added mapping is only relevant when importing into a world that has a different mapping itself.

I read over your schematic format spec. It looks like you use a variable number of bits to store each block ID depending on the size of the palette. I didn't care for this kind of bit packing when @Ivorforce suggested it to me, because I would need to unpack the bits to the next largest data type to use them with numpy arrays - indeed, the Recurrent Complex export format does the same kind of bit packing, but upon loading the exported structure, it will unpack the bits into a 32-bit integer, meaning that the bit packing is only a gain with regards to the on-disk size of the exported file and is actually a loss wrt the in-memory size. Looking at your own preliminary implementation, you will be unpacking the bits into an array of 16-bit integers, so there is no gain with in-memory size there either.

The on-disk size of schematics has never been a significant issue to me, due to the effectiveness of GZip compression and due to Entities and TileEntities often making gains in block ID compression insignificant. For schematics large enough where the in-memory size is an issue, I prefer to just use the world format itself as the export format. The world format being made of chunks makes the memory issue simply go away.
