### ISSUE TITLE
MC-Edit does not recognize minecraft version

### ISSUE THREAD

**Issue by chaos234** [mcedit/mcedit2#256]
Hi,

I don't have any MC-Version as default under /.minecraft installed.

I only use MultiMC to have a better overview of my instances but it also doesn't recognizes my FTB Infinity Eveolved Version which is linked in MultiMC.

Please fix this, thanks.

And in addition I thin the "inspect chunks" is working fals. Because for me such a function shouldn't tell me what I can found there ... it should tell me if the chank is broken or not which is definitly read able.

Please fix this also, thanks.

**Comment by codewarrior0** [comment]
The required Minecraft version will be downloaded automatically in the next release.

"Inspect Chunks" simply allows you to look at the raw NBT structure for a chunk and edit it at that low level. If a chunk is completely broken, it will not appear in MCEdit at all. I should add some indicator to tell the difference between chunks that aren't present and chunks that are present but are unreadable due to corruption - so you know you can delete the unreadable chunks.

**Comment by chaos234** [comment]
This will be glad :).
Am 24.08.2016 12:01:20 schrieb David Vierra <notifications@github.com>:
The required Minecraft version will be downloaded automatically in the next release.
"Inspect Chunks" simply allows you to look at the raw NBT structure for a chunk and edit it at that low level. If a chunk is completely broken, it will not appear in MCEdit at all. I should add some indicator to tell the difference between chunks that aren't present and chunks that are present but are unreadable due to corruption - so you know you can delete the unreadable chunks.

**Comment by codewarrior0** [comment]
Fixed in beta3
