### ISSUE TITLE
2nd width hovering is incorrect

### ISSUE THREAD

**Issue by acterhd** [mcedit/mcedit2#266]
Hello. I have problems with hovering 2 and fractable by 2. For example, brush. 
Problem with force rounding (i.e. flooring) coordinates. In floor (top block) brush (hover=1, as should if hover 2) in 1 block lower, but cube should be in block. In ceil (bottom block) normally, 1 block spacing from center. Same not only by Y, but in X and Z. 

I can no fix this issue in source code, I don't know how working this editor. For me very hard to fix even simple issue. 

Video: https://www.youtube.com/watch?v=Iarh5zUlaic

Also, center of brush also should be between cubes (in line).

**Comment by acterhd** [comment]
Проклятый Питон! Я не знаю что вы там наделали с кодом! Я не понимаю что вы сделали когда вы создавали редактор mcedit. Я не могу исправить с виду простую ошибку с пером, особенно при 2x2x2. Я ничего не могу поделать. Мне нужно четко знать все entry и output точки. Абсолютно все. Вы сделали настолько большой и запутанный редактор, что мне уже невозможно разобраться в коде. Так много приближений чисел. Не знаю можно свалить все на мои плохие знания в Питоне, если не ряд НО. Я программированием занимаюсь давно, еще с JS и C++. И провалы происходят не так часто. Разве что chromium... Такого сложно кода я еще ни разу не видел. Здесь же слишком много черного ящика.

**Comment by codewarrior0** [comment]
The problem isn't with the hover setting. What you describe happens with any setting. It's just that even sized brushes necessarily have their "center point" off center because an even integer number of blocks has no block at the exact center. Even if the center of the brush were represented as a float, so you got 0.5 as the center when the size is *odd*, you would still have to decide whether to round it up or down to align it to the block grid according to whether the vector of the block face under the cursor is positive or negative - which is the exact same solution as when using integer coordinates.

Also, you didn't read the guidelines.

**Comment by acterhd** [comment]
I undertanding, but why not make 2x center as float i.e. 0.5?

**Comment by codewarrior0** [comment]
>you would still have to decide whether to round it up or down to align it to the block grid

**Comment by acterhd** [comment]
I want building in macro sizes, like stairs, slabs... 
For that need not standard features.

**Comment by acterhd** [comment]
Please, rewrite ray casting code for getting float values. I researched all, but understand that ray casting giving only rounded values, even if disable intfloor.

**Comment by acterhd** [comment]
I can not load fork...
