### ISSUE TITLE
2.0.0-beta 8 crashes on startup

### ISSUE THREAD

**Issue by cdfa** [mcedit/mcedit2#336]
Hi, I just downloaded the new beta, but it crashes on startup with the 64 bit and 32 bit version. I'm on Windows 10 64 bit. [Here's the log](https://pastebin.com/WxYvfh5F)

**Comment by Hacksolot** [comment]
that is the exact same error as mine, i am using 64-bit windows 7 pro

**Comment by AstroTibs** [comment]
I'm having the same issue and I reported this on the subreddit.
Beta 6 and 7 load on my Win 8.1 laptop and my Win 10 desktop. Beta 8 crashes on both due to (I think) a package import problem.
[Console screencap](http://imgur.com/a/FEnMi)
Python version on both machines is **2.7.9**. I wonder if this has something to do with it?

**Comment by codewarrior0** [comment]
Resolved in beta9. Was indeed a missing package option.
