### ISSUE TITLE
world generation

### ISSUE THREAD

**Issue by Gowcu** [mcedit/mcedit2#86]
This isn't really a problem, but is there a way to make mcedit load/generate chunks on a map that  has world generation mods such as real world generator, biomes o plenty, and big trees? The one time I tried I'm pretty sure it was using vanilla generation.

**Comment by codewarrior0** [comment]
Yes, theoretically. You would need to set up a modded server with all of those mods and the same configs as your modded client, and then get MCEdit to use that server to generate chunks instead of a vanilla server.

Because of the startup time of modded servers this could take forever. I recommend using something like Admin Commands Toolbox to generate chunks in-game.

Closing as this is definitely not a MCEdit 2.0 issue.
